theme: jekyll-theme-minimal
title: AutoClicker2 Record Play (The Lists Of Mouse Clicks)
description: Open source mouse auto-clicker to record, edit, import, debug, and playback the whole sequences of mouse clicks with 5 mouse buttons.  Advanced 2022 fork of frozen or proprietary opautoclicker.com, sourceforge.net, autoclicker.io, autoclicker.org, macrorecorder.com, remouse.com, etc.
